# SPDX-FileCopyrightText: Joonas Javanainen <joonas.javanainen@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[toolchain]
channel = "nightly-2023-11-01"
components = ["rustfmt", "clippy"]
profile = "minimal"
